<?php
/**
 *  config.inc
 *
 * Configuration for BappNet
 *
 * @author     Bo Grus
 * @copyright  2015 Bo Grus
*/

$siteName = 'Digital Master';


define('SITE', 'http://locahlost/bappnet-p1/app');
define('ARCHIVE', '../arkiv');
define('DOCVIEW', 'http://localhost/bappnet-p/arkiv/');
/*
define('DB_HOST',  'localhost');
define('DB_NAME', 'dm');
define('DB_USER', 'root');
define('DB_PASS', 'segdeg');
*/
define('DB_SECURITY_HOST',  'mysql.vmi.se');
define('DB_SECURITY_NAME', 'devbappnetse');
define('DB_SECURITY_USER', 'devbappnetse'); 
define('DB_SECURITY_PASS', 'PbBXx');
